//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string ProductId { get; set; }
        public int Number { get; set; }
        public int NumberGiven { get; set; }
        public long OriginalPrice { get; set; }
        public long FinalPrice { get; set; }
        public string Event { get; set; }
        public bool GoToShop { get; set; }
        public Nullable<long> MoneyTaken { get; set; }
        public Nullable<long> MoneyExchange { get; set; }
        public string Address { get; set; }
        public Nullable<long> Deposit { get; set; }
        public Nullable<long> Ship { get; set; }
        public Nullable<long> MoneyWillGet { get; set; }
        public string Status { get; set; }
    }
}
