//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public string Name { get; set; }
        public System.DateTime DateBegin { get; set; }
        public System.DateTime DateEnd { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> BuyGet_Buy { get; set; }
        public Nullable<int> BuyGet_Get { get; set; }
    }
}
