//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Name { get; set; }
        public string Id { get; set; }
        public long Price { get; set; }
        public System.DateTime Date { get; set; }
        public int InitialAmount { get; set; }
        public int CurrentAmount { get; set; }
        public long Capital { get; set; }
        public string Description { get; set; }
        public string ProductType { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ProductType ProductTypes { get; set; }
    }
}
